#!/bin/bash

# Display the read/write speeds per second for sda and zram, in a table format
echo -e "Device\t\tRead (kB/s)\tWrite (kB/s)"

# Get disk stats using iostat and filter for 'sda' and 'zram0'
iostat -d 1 1 | awk '
    NR > 3 && ($1 == "sda" || $1 == "zram0") {
        printf "%-8s\t%-15s%-15s\n", $1, $3, $4
    }
'
